//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuraInventarioProto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuraInventarioProtoDBEntities : DbContext
    {
        public AuraInventarioProtoDBEntities()
            : base("name=AuraInventarioProtoDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DETMAN> DETMAN { get; set; }
        public virtual DbSet<INV_PC> INV_PC { get; set; }
        public virtual DbSet<LOGIN> LOGIN { get; set; }
        public virtual DbSet<MOVIMIENTOS_PC> MOVIMIENTOS_PC { get; set; }
        public virtual DbSet<UNE> UNE { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
