//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuraInventarioProto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class DETMAN
    {
        public int ID { get; set; }
        public string SERIAL { get; set; }
        public string MODELO { get; set; }
        public string MARCA { get; set; }
        public string TIPO { get; set; }
        public string ESTADO { get; set; }
        public string OBS { get; set; }
        public System.DateTime FECHA_ADQ { get; set; }
        public bool EST_TW { get; set; }
        public bool EST_CC { get; set; }
        public bool EST_AV { get; set; }
        public bool EST_PD { get; set; }
        public bool EST_OF { get; set; }
        public bool EST_WN { get; set; }
        public bool EST_REG { get; set; }
        public bool SGI_SW { get; set; }
        public bool SGI_RES { get; set; }
        public System.DateTime F_UL_MAN { get; set; }
        public string DEVU { get; set; }
        public string ASIGN { get; set; }
        public string OBRA { get; set; }
    }
}
