//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuraInventarioProto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class LOGIN
    {
        public int ID { get; set; }

        [Display(Name = "Usuario:")]
        [Required(ErrorMessage = "Error, Usuario es requerido.")]
        [MaxLength(30, ErrorMessage = "Error, El Usuario tiene un limite de 30 caracteres.")]
        [Remote("doesNameExist", "LOGIN", HttpMethod = "POST", ErrorMessage = "Error, El Usuario ya existe.")]
        public string NOMBRE { get; set; }

        [Display(Name = "Clave:")]
        [Required(ErrorMessage = "Error, Clave es requerida.")]
        [MinLength(4, ErrorMessage = "Error, Campo necesita almenos 4 caracteres.")]
        public string PASS { get; set; }

        public string SALT { get; set; }
    }
}
