//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuraInventarioProto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class LOGIN
    {
        public int ID { get; set; }

        [Display(Name = "Rut")]
        [RegularExpression(pattern: "[0-9]{2}[0-9]{3}[0-9]{3}-[k-k0-9]{1}", ErrorMessage = "Error, Favor entrar un Rut valido, ejemplo '12345678-k'.")]
        //[Required(ErrorMessage = "Error, Rut es requerido.")]
        [MaxLength(12, ErrorMessage = "Error, El Rut tiene un limite de 12 caracteres.")]
        [Remote("doesRutExist", "LOGIN", HttpMethod = "POST", ErrorMessage = "Error, El Usuario no existe.")]
        public string RUT { get; set; }

        [Display(Name = "Correo")]
        [Required(ErrorMessage = "Error, Correo es requerido.")]
        [EmailAddress(ErrorMessage = "Favor entrar un Correo valido.")]
        [MaxLength(30, ErrorMessage = "Error, El Correo tiene un limite de 30 caracteres.")]
        [Remote("doesCorreoExist", "LOGIN", HttpMethod = "POST", ErrorMessage = "Error, El Correo no existe.")]
        public string CORREO { get; set; }

        [Display(Name = "Clave")]
        [Required(ErrorMessage = "Error, Clave es requerido.")]
        [MinLength(4, ErrorMessage = "Error, Campo necesita almenos 4 caracteres.")]
        public string PASS { get; set; }

        //[Required(ErrorMessage = "Error, Salt es requerido.")]
        public string SALT { get; set; }
    }
}
