//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuraInventarioProto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class MOVIMIENTOS_PC
    {
        public int ID { get; set; }

        [Display(Name = "Rut Usuario")]
        [Required(ErrorMessage = "Error, Rut es requerido.")]
        [RegularExpression(pattern: "[0-9]{2}[0-9]{3}[0-9]{3}-[k-k0-9]{1}", ErrorMessage = "Error, Favor entrar un Rut valido, ejemplo '12345678-k'.")]
        [MaxLength(12, ErrorMessage = "Error, El Rut tiene un limite de 12 caracteres.")]
        [Remote("doesRutExist", "USUARIOS", HttpMethod = "POST", ErrorMessage = "Error, El Usuario ya existe.")]
        public string RUT_USUARIO { get; set; }

        [Display(Name = "Serial Pc")]
        [Required(ErrorMessage = "Error, Serial es requerido")]
        [MaxLength(30, ErrorMessage = "Error, Campo tiene un limite de 30 caracteres.")]
        public string ID_PC { get; set; }

        [Display(Name = "Tipo de Movimiento")]
        [Required(ErrorMessage = "Error, Tipo es requerido")]
        [MaxLength(30, ErrorMessage = "Error, Campo tiene un limite de 30 caracteres.")]
        public string TIPO_MOV { get; set; }

        [Display(Name = "Fecha Asignacion")]
        public Nullable<System.DateTime> FECHA_AS { get; set; }

        [Display(Name = "Fecha Devolucion")]
        public Nullable<System.DateTime> FECHA_DV { get; set; }

        [Display(Name = "Fecha Movimiento")]
        [Required(ErrorMessage = "Error, Fecha es requerido")]
        public System.DateTime FECHA_MOV { get; set; }
    }
}
