//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuraInventarioProto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class MOVIMIENTOS_PC
    {
        public int ID { get; set; }
        public string RUT_USUARIO { get; set; }
        public string ID_PC { get; set; }
        public string TIPO_MOV { get; set; }
        public System.DateTime FECHA_MOV { get; set; }
        public string OBS { get; set; }
    }
}
