//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuraInventarioProto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class MOVIMIENTOS_PC
    {
        public int ID { get; set; }
        public string RUT_USUARIO { get; set; }
        public string ID_PC { get; set; }
        public string TIPO_MOV { get; set; }
        public System.DateTime FECHA_MOV { get; set; }
        public string OBS { get; set; }
    }
}
