//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuraInventarioProto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class USUARIOS
    {
        public int ID { get; set; }
        public string RUT { get; set; }
        public string NOMBRE_C { get; set; }
        public string CORREO { get; set; }
        public string UNE { get; set; }
        public string ESTADO { get; set; }
    }
}
