//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuraInventarioProto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class View_serial_correo
    {
        public string NOMBRE_C { get; set; }
        public string SERIAL { get; set; }
        public string MARCA { get; set; }
        public string RUT { get; set; }
        public string CORREO { get; set; }
        public int ID { get; set; }
    }
}
